/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __create = Object.create;
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __getProtoOf = Object.getPrototypeOf;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toESM = (mod, isNodeMode, target) => (target = mod != null ? __create(__getProtoOf(mod)) : {}, __copyProps(
  // If the importer is in node compatibility mode or this is not an ESM
  // file that has been converted to a CommonJS file using a Babel-
  // compatible transform (i.e. "__esModule" has not been set), then set
  // "default" to the CommonJS "module.exports" for node compatibility.
  isNodeMode || !mod || !mod.__esModule ? __defProp(target, "default", { value: mod, enumerable: true }) : target,
  mod
));
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => main_default
});
module.exports = __toCommonJS(main_exports);

// src/plugin.ts
var import_obsidian3 = require("obsidian");

// src/settings.ts
var import_obsidian = require("obsidian");
var DEFAULT_SETTINGS = {
  enabledLocalRepo: false,
  gitRepo: "",
  hexoSourceDir: "source"
};
var HexoPublisherPluginSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app2, plugin) {
    super(app2, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h1", { text: "Settings" });
    new import_obsidian.Setting(containerEl).setName("Git Repo").setDesc("git repo path for hexo site.").addText((text) => text.setPlaceholder("Enter your git repo").setValue(this.plugin.settings.gitRepo).onChange(async (value) => {
      this.plugin.settings.gitRepo = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Source Dir").setDesc("Source dir for hexo site.").addText((text) => text.setPlaceholder("source").setValue(this.plugin.settings.hexoSourceDir).onChange(async (value) => {
      this.plugin.settings.gitRepo = value;
      await this.plugin.saveSettings();
    }));
  }
};

// src/commands.ts
var import_obsidian2 = require("obsidian");

// src/hexo.ts
var path = __toESM(require("path"));
var fs = __toESM(require("fs"));
var Hexo = class {
  constructor(root, sourceDir = "source") {
    this.root = root;
    this.sourceDir = sourceDir;
    this.postFolder = path.join(sourceDir, "_posts");
    this.imageFolder = path.join(sourceDir, "images");
    ;
  }
  getPostFolderPath() {
    return path.join(this.root, this.postFolder);
  }
  getImageFolderPath() {
    return path.join(this.root, this.imageFolder);
  }
  getPostPath(name) {
    return path.join(this.getPostFolderPath(), name);
  }
  getImagePath(name) {
    return path.join(this.getImageFolderPath(), name);
  }
  normalizeMarkdown(markdown) {
    let normalizedMarkdown = markdown;
    const imageFolder = this.imageFolder.replace(this.sourceDir, "/");
    normalizedMarkdown = normalizedMarkdown.replace(/\^\[([^\]]+)\]/g, "<!-- $1 -->");
    normalizedMarkdown = normalizedMarkdown.replace(/!\[([^\]]+)\]\(([^)]+)\)/g, `![$1](/images/$2)`);
    normalizedMarkdown = normalizedMarkdown.replace(/!\[\[([^\]]+)\]\]/g, "![$1](/images/$1)");
    return normalizedMarkdown;
  }
  async writePost(name, content) {
    const postPath = this.getPostPath(name);
    try {
      await fs.promises.mkdir(path.dirname(postPath), { recursive: true });
      await fs.promises.writeFile(postPath, content, "utf8");
      console.log(`Post written to: ${postPath}`);
    } catch (error) {
      console.error(`Error writing post: ${error}`);
    }
  }
  async writeImage(name, content) {
    const imagePath = this.getImagePath(name);
    try {
      await fs.promises.mkdir(path.dirname(imagePath), { recursive: true });
      await fs.promises.writeFile(imagePath, Buffer.from(content));
      console.log(`Image written to: ${imagePath}`);
    } catch (error) {
      console.error(`Error writing image: ${error}`);
    }
  }
};

// src/helpers.ts
var ObsidianHelper = class {
  constructor(app2) {
    this.app = app2;
  }
  getFileByPath(name) {
    let files = this.app.vault.getFiles();
    let file = files.find((file2) => file2.name === name);
    return file;
  }
  getPublishedPosts() {
    const markdownFiles = this.app.vault.getMarkdownFiles();
    console.log(`Found ${markdownFiles.length} markdown files`);
    const publishedPosts = [];
    for (const file of markdownFiles) {
      const metadataCache = app.metadataCache.getFileCache(file);
      if (metadataCache && metadataCache.frontmatter && metadataCache.frontmatter.publish === true) {
        publishedPosts.push(file);
      }
    }
    return publishedPosts;
  }
};

// src/utils.ts
var Utils = class {
  static extractImages(obsidianMarkdown) {
    const images = [];
    const imageRegex = /!\[\[([^\]]+)\]\]/g;
    let match;
    while ((match = imageRegex.exec(obsidianMarkdown)) !== null) {
      images.push(match[1]);
    }
    return images;
  }
};

// src/commands.ts
function syncCommand(app2, settings) {
  return {
    id: "publish-command",
    name: "Publish Posts",
    callback: () => {
      publishPosts(app2, settings);
    }
  };
}
async function publishPosts(app2, settings) {
  const helpers = new ObsidianHelper(app2);
  const publishedPosts = await helpers.getPublishedPosts();
  console.log(`Found ${publishedPosts.length} posts need to publish.`);
  if (publishedPosts.length === 0) {
    new import_obsidian2.Notice("No posts need to publish.");
    return;
  }
  const hexo = new Hexo(settings.gitRepo);
  for (const mdFile of publishedPosts) {
    try {
      const content = await mdFile.vault.read(mdFile);
      const images = Utils.extractImages(content);
      if (images.length > 0) {
        console.log(`Found ${images.length} images in ${mdFile.name}`);
        for (const image of images) {
          const imageFile = helpers.getFileByPath(image);
          if (imageFile == null ? void 0 : imageFile.path) {
            const imageContent = await imageFile.vault.readBinary(imageFile);
            await hexo.writeImage(image, imageContent);
          }
        }
      }
      const normalized = hexo.normalizeMarkdown(content);
      await hexo.writePost(mdFile.name, normalized);
    } catch (error) {
      console.error(`Failed to read file ${mdFile}\uFF1A${error}`);
    }
  }
  new import_obsidian2.Notice(`Synced ${publishedPosts.length} posts`);
}

// src/plugin.ts
var HexoPublisher = class extends import_obsidian3.Plugin {
  async onload() {
    await this.loadSettings();
    this.addCommand(syncCommand(this.app, this.settings));
    this.addSettingTab(new HexoPublisherPluginSettingTab(this.app, this));
    this.addRibbonIcon("webhook", "Publish posts to hexo", () => {
      publishPosts(this.app, this.settings);
    });
  }
  onunload() {
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
};

// src/main.ts
var main_default = HexoPublisher;
